apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: radio
build:
  artifacts:
  - image: shokohsc/radio-server
    context: .
    sync:
      manual:
      - src: index.js
        dest: .
    docker:
      dockerfile: Dockerfile.dev
  - image: shokohsc/radio-ui
    context: ./frontend
    sync:
      manual:
      - src: src/main.js
        dest: .
      - src: src/App.vue
        dest: .
      - src: index.html
        dest: .
    docker:
      dockerfile: Dockerfile.dev
deploy:
  kustomize:
    paths:
    - k8s/base
profiles:
- name: dev
  activation:
  - command: dev
  build:
    artifacts:
    - image: shokohsc/radio-server
      context: .
      sync:
        manual:
        - src: index.js
          dest: .
    - image: shokohsc/radio-ui
      context: ./frontend
      sync:
        manual:
        - src: src/main.js
          dest: .
        - src: src/App.vue
          dest: .
        - src: index.html
          dest: .
- name: shokohsc
  build:
    artifacts:
    - image: shokohsc/radio-server
      context: .
      sync:
        manual:
        - src: index.js
          dest: .
      kaniko:
        useNewRun: true
        cache:
          repo: shokohsc/radio-server
        dockerfile: Dockerfile.dev
    - image: shokohsc/radio-ui
      context: ./frontend
      sync:
        manual:
        - src: src/main.js
          dest: .
        - src: src/App.vue
          dest: .
        - src: index.html
          dest: .
      kaniko:
        useNewRun: true
        cache:
          repo: shokohsc/radio-ui
        dockerfile: Dockerfile.dev
    cluster:
      dockerConfig:
        secretName: kaniko-secret
      namespace: kaniko
      pullSecretName: kaniko-secret
      resources:
        limits:
          cpu: "2"
          memory: 2Gi
        requests:
          cpu: "1"
          memory: 1Gi
  deploy:
    kustomize:
      paths:
      - k8s/overlays/shokohsc
- name: prod
  build:
    artifacts:
    - image: shokohsc/radio-server
      context: .
      kaniko:
        useNewRun: true
        cache:
          repo: shokohsc/radio-server
        dockerfile: Dockerfile
    - image: shokohsc/radio-ui
      context: ./frontend
      kaniko:
        useNewRun: true
        cache:
          repo: shokohsc/radio-ui
        dockerfile: Dockerfile
        buildArgs:
          POD_NAME: '{{.GIT_COMMIT}}'
          SENTRY_AUTH_TOKEN: db6ff5f7b002322a0b6800027fa823d5faa131dc2535e060375d902728ea8353
          SENTRY_PROJECT: radio
    cluster:
      dockerConfig:
        secretName: kaniko-secret
      namespace: kaniko
      pullSecretName: kaniko-secret
      resources:
        limits:
          cpu: "2"
          memory: 2Gi
        requests:
          cpu: "1"
          memory: 1Gi
